package cli

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// The Homebrew formula generated by shhac/homebrew-tap's go-release workflow
// asserts `help_match` appears in `agent-dlocal --help`. That assertion runs at
// RELEASE time, so a reworded Short string does not fail the build, the tests,
// or CI — it fails the tag push, after the GitHub Release has already been
// published. Pinning the invariant here moves the failure to where it is cheap.
func TestReleaseHelpMatchAppearsInRootShort(t *testing.T) {
	helpMatch := releaseWorkflowInput(t, "help_match")
	short := newRootCmd("test").Short

	if !strings.Contains(short, helpMatch) {
		t.Fatalf("release.yml help_match is not a substring of the root command's Short.\n"+
			"  help_match: %q\n"+
			"  Short:      %q\n"+
			"The generated Homebrew formula asserts this against `agent-dlocal --help`, "+
			"so releasing would fail after the release is already published.", helpMatch, short)
	}
}

// The formula's desc is what `brew info` shows. Homebrew's audit rejects a desc
// over 80 characters, which is easy to trip when the description is edited to
// match a reworded Short.
func TestReleaseDescIsWithinHomebrewLimit(t *testing.T) {
	desc := releaseWorkflowInput(t, "desc")

	if len(desc) > 80 {
		t.Fatalf("release.yml desc is %d characters; Homebrew's audit rejects over 80:\n  %q", len(desc), desc)
	}
	if desc == "" {
		t.Fatal("release.yml has no desc; the formula needs one")
	}
}

// releaseWorkflowInput pulls one `key: value` input out of release.yml.
// A line scan rather than a YAML parse: the file is a fixed shape we control,
// and the test should fail loudly if that shape changes rather than silently
// finding nothing.
func releaseWorkflowInput(t *testing.T, key string) string {
	t.Helper()

	path := filepath.Join("..", "..", ".github", "workflows", "release.yml")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}

	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		value, found := strings.CutPrefix(trimmed, key+":")
		if !found {
			continue
		}
		value = strings.TrimSpace(value)
		if unquoted, err := strconv.Unquote(value); err == nil {
			return unquoted
		}
		return value
	}

	t.Fatalf("release.yml has no %q input; the release workflow's shape changed", key)
	return ""
}
